language: java
sudo: false

before_install: echo "MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx1g -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS'" > ~/.mavenrc

script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jdk:
- oraclejdk8

cache:
  directories:
  - ~/.m2
